version: '3.9'

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - fastapi

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
      args:
        GUARDRAILS_TOKEN: ${GUARDRAILS_TOKEN}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
